#!/bin/bash
#PBS -l nodes=1:ppn=1:dc2
#PBS -l walltime=0:10:00
#PBS -N makeblastdb
#PBS -V

echo "env available to psb script"
set | grep SCA | sort
set | grep PBS | sort

echo "go back to SCA TASK DIR"
cd $PBS_O_WORKDIR

#aprun -n 1 ~/.sca/services/blast_makedb/makedb.sh

#enable nodejs stuff
export PATH=$PATH:~/.sca/bin/node/bin
export PATH=$PATH:~/.sca/node_modules/underscore-cli/bin

progress_url="{$SCA_PROGRESS_URL}/{$SCA_PROGRESS_KEY}.makeblastdb"
dbtype=`cat $SCA_TASK_DIR_FASTA/products.json | underscore select '.fasta .type' --outfmt text`
dbtitle=sometitle
dbname=somedb
input_file=`cat $SCA_TASK_DIR_FASTA/products.json | underscore select '.fasta .filename' --outfmt text`
input_filepath=$SCA_TASK_DIR_FASTA/$input_file

curl -X POST -H "Content-Type: application/json" -d "{\"name\": \"$dbname\", \"status\": \"running\", \"progress\": 0, \"msg\":\"Building DB\"}" $progress_url

module load ncbi-blast+

#USAGE
#  makeblastdb [-h] [-help] [-in input_file] [-input_type type]
#    -dbtype molecule_type [-title database_title] [-parse_seqids]
#    [-hash_index] [-mask_data mask_data_files] [-gi_mask]
#    [-gi_mask_name gi_based_mask_names] [-out database_name]
#    [-max_file_sz number_of_bytes] [-taxid TaxID] [-taxid_map TaxIDMapFile]
#    [-logfile File_Name] [-version]
echo "aprun -n 1 makeblastdb -in $input_filepath -title $input_file -dbtype $dbtype -out $dbname"
aprun -n 1 makeblastdb -in $input_filepath -title $input_file -dbtype $dbtype -out $dbname
ret=$?
echo $ret > exit.code
if [ $ret -eq 0 ]
then
    status="finished"
    msg="Successfully built blast DB"
    echo "[{\"type\": \"bio/blastdb\", \"name\": \"$dbname\", \"dbtype\": \"$dbtype\", \"source\":\"user\"}]" > products.json
else
    status="failed"
    msg="makeblastdb returned code:$ret"
fi
curl -X POST -H "Content-Type: application/json" -d "{\"status\": \"finished\", \"progress\": 1, \"msg\":\"Finished Building DB\"}" $progress_url

rm running
exit $ret

